package st

import (
	"sunny/rooui/ui"
)

// this file is generated by go:generate, DO NOT EDIT.

// https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color
func AccentColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("accent-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/align-content
func AlignContent(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("align-content", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/align-items
func AlignItems(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("align-items", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/align-self
func AlignSelf(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("align-self", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/align-tracks
func AlignTracks(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("align-tracks", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/all
func All(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("all", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/animation
func Animation(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("animation", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/animation-composition
func AnimationComposition(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("animation-composition", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/animation-delay
func AnimationDelay(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("animation-delay", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/animation-direction
func AnimationDirection(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("animation-direction", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/animation-duration
func AnimationDuration(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("animation-duration", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode
func AnimationFillMode(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("animation-fill-mode", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/animation-iteration-count
func AnimationIterationCount(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("animation-iteration-count", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/animation-name
func AnimationName(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("animation-name", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/animation-play-state
func AnimationPlayState(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("animation-play-state", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline
func AnimationTimeline(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("animation-timeline", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function
func AnimationTimingFunction(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("animation-timing-function", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/appearance
func Appearance(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("appearance", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio
func AspectRatio(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("aspect-ratio", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter
func BackdropFilter(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("backdrop-filter", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/backface-visibility
func BackfaceVisibility(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("backface-visibility", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/background
func Background(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("background", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment
func BackgroundAttachment(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("background-attachment", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/background-blend-mode
func BackgroundBlendMode(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("background-blend-mode", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip
func BackgroundClip(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("background-clip", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/background-color
func BackgroundColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("background-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/background-image
func BackgroundImage(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("background-image", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/background-origin
func BackgroundOrigin(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("background-origin", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/background-position
func BackgroundPosition(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("background-position", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-x
func BackgroundPositionX(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("background-position-x", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-y
func BackgroundPositionY(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("background-position-y", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/background-repeat
func BackgroundRepeat(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("background-repeat", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/background-size
func BackgroundSize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("background-size", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/block-size
func BlockSize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("block-size", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border
func Border(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-block
func BorderBlock(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-block", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-color
func BorderBlockColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-block-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-end
func BorderBlockEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-block-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-end-color
func BorderBlockEndColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-block-end-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-end-style
func BorderBlockEndStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-block-end-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-end-width
func BorderBlockEndWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-block-end-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-start
func BorderBlockStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-block-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-start-color
func BorderBlockStartColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-block-start-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-start-style
func BorderBlockStartStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-block-start-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-start-width
func BorderBlockStartWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-block-start-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-style
func BorderBlockStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-block-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-width
func BorderBlockWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-block-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom
func BorderBottom(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-bottom", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-color
func BorderBottomColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-bottom-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-left-radius
func BorderBottomLeftRadius(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-bottom-left-radius", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-right-radius
func BorderBottomRightRadius(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-bottom-right-radius", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-style
func BorderBottomStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-bottom-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-width
func BorderBottomWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-bottom-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-collapse
func BorderCollapse(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-collapse", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-color
func BorderColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-end-end-radius
func BorderEndEndRadius(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-end-end-radius", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-end-start-radius
func BorderEndStartRadius(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-end-start-radius", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-image
func BorderImage(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-image", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-outset
func BorderImageOutset(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-image-outset", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-repeat
func BorderImageRepeat(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-image-repeat", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice
func BorderImageSlice(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-image-slice", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-source
func BorderImageSource(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-image-source", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-width
func BorderImageWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-image-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline
func BorderInline(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-inline", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-color
func BorderInlineColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-inline-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-end
func BorderInlineEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-inline-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-end-color
func BorderInlineEndColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-inline-end-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-end-style
func BorderInlineEndStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-inline-end-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-end-width
func BorderInlineEndWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-inline-end-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-start
func BorderInlineStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-inline-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-start-color
func BorderInlineStartColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-inline-start-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-start-style
func BorderInlineStartStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-inline-start-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-start-width
func BorderInlineStartWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-inline-start-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-style
func BorderInlineStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-inline-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-width
func BorderInlineWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-inline-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-left
func BorderLeft(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-left", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-left-color
func BorderLeftColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-left-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-left-style
func BorderLeftStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-left-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-left-width
func BorderLeftWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-left-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius
func BorderRadius(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-radius", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-right
func BorderRight(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-right", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-right-color
func BorderRightColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-right-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-right-style
func BorderRightStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-right-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-right-width
func BorderRightWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-right-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-spacing
func BorderSpacing(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-spacing", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-start-end-radius
func BorderStartEndRadius(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-start-end-radius", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-start-start-radius
func BorderStartStartRadius(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-start-start-radius", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-style
func BorderStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-top
func BorderTop(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-top", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-color
func BorderTopColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-top-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-left-radius
func BorderTopLeftRadius(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-top-left-radius", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-right-radius
func BorderTopRightRadius(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-top-right-radius", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-style
func BorderTopStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-top-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-width
func BorderTopWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-top-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/border-width
func BorderWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("border-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/bottom
func Bottom(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("bottom", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break
func BoxDecorationBreak(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("box-decoration-break", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow
func BoxShadow(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("box-shadow", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing
func BoxSizing(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("box-sizing", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/break-after
func BreakAfter(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("break-after", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/break-before
func BreakBefore(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("break-before", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/break-inside
func BreakInside(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("break-inside", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/caption-side
func CaptionSide(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("caption-side", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color
func CaretColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("caret-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/clear
func Clear(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("clear", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path
func ClipPath(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("clip-path", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/color
func Color(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme
func ColorScheme(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("color-scheme", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/column-count
func ColumnCount(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("column-count", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/column-fill
func ColumnFill(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("column-fill", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap
func ColumnGap(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("column-gap", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/column-rule
func ColumnRule(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("column-rule", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/column-rule-color
func ColumnRuleColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("column-rule-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/column-rule-style
func ColumnRuleStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("column-rule-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/column-rule-width
func ColumnRuleWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("column-rule-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/column-span
func ColumnSpan(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("column-span", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/column-width
func ColumnWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("column-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/columns
func Columns(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("columns", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/contain
func Contain(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("contain", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-block-size
func ContainIntrinsicBlockSize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("contain-intrinsic-block-size", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-height
func ContainIntrinsicHeight(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("contain-intrinsic-height", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-inline-size
func ContainIntrinsicInlineSize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("contain-intrinsic-inline-size", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-size
func ContainIntrinsicSize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("contain-intrinsic-size", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-width
func ContainIntrinsicWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("contain-intrinsic-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/container
func Container(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("container", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/container-name
func ContainerName(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("container-name", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/container-type
func ContainerType(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("container-type", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/content
func Content(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("content", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility
func ContentVisibility(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("content-visibility", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/counter-increment
func CounterIncrement(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("counter-increment", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/counter-reset
func CounterReset(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("counter-reset", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/counter-set
func CounterSet(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("counter-set", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
func Cursor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("cursor", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/direction
func Direction(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("direction", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/display
func Display(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("display", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/empty-cells
func EmptyCells(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("empty-cells", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/filter
func Filter(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("filter", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/flex
func Flex(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("flex", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis
func FlexBasis(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("flex-basis", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction
func FlexDirection(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("flex-direction", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/flex-flow
func FlexFlow(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("flex-flow", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/flex-grow
func FlexGrow(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("flex-grow", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/flex-shrink
func FlexShrink(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("flex-shrink", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap
func FlexWrap(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("flex-wrap", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/float
func Float(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("float", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font
func Font(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
func FontFamily(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-family", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings
func FontFeatureSettings(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-feature-settings", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-kerning
func FontKerning(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-kerning", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-language-override
func FontLanguageOverride(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-language-override", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-optical-sizing
func FontOpticalSizing(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-optical-sizing", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-palette
func FontPalette(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-palette", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-size
func FontSize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-size", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust
func FontSizeAdjust(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-size-adjust", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth
func FontSmooth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-smooth", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch
func FontStretch(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-stretch", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-style
func FontStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis
func FontSynthesis(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-synthesis", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant
func FontVariant(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-variant", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates
func FontVariantAlternates(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-variant-alternates", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-caps
func FontVariantCaps(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-variant-caps", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-east-asian
func FontVariantEastAsian(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-variant-east-asian", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-emoji
func FontVariantEmoji(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-variant-emoji", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures
func FontVariantLigatures(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-variant-ligatures", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric
func FontVariantNumeric(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-variant-numeric", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-position
func FontVariantPosition(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-variant-position", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-variation-settings
func FontVariationSettings(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-variation-settings", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight
func FontWeight(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("font-weight", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/forced-color-adjust
func ForcedColorAdjust(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("forced-color-adjust", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/gap
func Gap(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("gap", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid
func Grid(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-area
func GridArea(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-area", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-columns
func GridAutoColumns(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-auto-columns", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-flow
func GridAutoFlow(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-auto-flow", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-rows
func GridAutoRows(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-auto-rows", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column
func GridColumn(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-column", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column-end
func GridColumnEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-column-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column-start
func GridColumnStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-column-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row
func GridRow(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-row", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row-end
func GridRowEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-row-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row-start
func GridRowStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-row-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template
func GridTemplate(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-template", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas
func GridTemplateAreas(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-template-areas", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns
func GridTemplateColumns(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-template-columns", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-rows
func GridTemplateRows(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("grid-template-rows", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/hanging-punctuation
func HangingPunctuation(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("hanging-punctuation", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/height
func Height(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("height", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/hyphenate-character
func HyphenateCharacter(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("hyphenate-character", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/hyphenate-limit-chars
func HyphenateLimitChars(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("hyphenate-limit-chars", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens
func Hyphens(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("hyphens", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation
func ImageOrientation(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("image-orientation", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering
func ImageRendering(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("image-rendering", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/image-resolution
func ImageResolution(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("image-resolution", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/initial-letter
func InitialLetter(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("initial-letter", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/initial-letter-align
func InitialLetterAlign(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("initial-letter-align", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/inline-size
func InlineSize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("inline-size", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/inset
func Inset(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("inset", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/inset-block
func InsetBlock(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("inset-block", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/inset-block-end
func InsetBlockEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("inset-block-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/inset-block-start
func InsetBlockStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("inset-block-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/inset-inline
func InsetInline(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("inset-inline", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/inset-inline-end
func InsetInlineEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("inset-inline-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/inset-inline-start
func InsetInlineStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("inset-inline-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/isolation
func Isolation(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("isolation", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content
func JustifyContent(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("justify-content", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/justify-items
func JustifyItems(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("justify-items", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self
func JustifySelf(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("justify-self", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/justify-tracks
func JustifyTracks(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("justify-tracks", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/left
func Left(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("left", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing
func LetterSpacing(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("letter-spacing", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/line-break
func LineBreak(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("line-break", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/line-height
func LineHeight(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("line-height", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/line-height-step
func LineHeightStep(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("line-height-step", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/list-style
func ListStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("list-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-image
func ListStyleImage(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("list-style-image", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position
func ListStylePosition(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("list-style-position", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type
func ListStyleType(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("list-style-type", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/margin
func Margin(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("margin", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/margin-block
func MarginBlock(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("margin-block", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/margin-block-end
func MarginBlockEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("margin-block-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/margin-block-start
func MarginBlockStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("margin-block-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/margin-bottom
func MarginBottom(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("margin-bottom", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline
func MarginInline(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("margin-inline", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-end
func MarginInlineEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("margin-inline-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-start
func MarginInlineStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("margin-inline-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/margin-left
func MarginLeft(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("margin-left", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/margin-right
func MarginRight(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("margin-right", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/margin-top
func MarginTop(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("margin-top", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/margin-trim
func MarginTrim(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("margin-trim", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask
func Mask(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-border
func MaskBorder(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-border", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-border-mode
func MaskBorderMode(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-border-mode", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-border-outset
func MaskBorderOutset(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-border-outset", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-border-repeat
func MaskBorderRepeat(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-border-repeat", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-border-slice
func MaskBorderSlice(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-border-slice", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-border-source
func MaskBorderSource(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-border-source", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-border-width
func MaskBorderWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-border-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-clip
func MaskClip(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-clip", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-composite
func MaskComposite(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-composite", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image
func MaskImage(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-image", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-mode
func MaskMode(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-mode", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-origin
func MaskOrigin(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-origin", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-position
func MaskPosition(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-position", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-repeat
func MaskRepeat(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-repeat", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-size
func MaskSize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-size", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mask-type
func MaskType(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mask-type", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/masonry-auto-flow
func MasonryAutoFlow(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("masonry-auto-flow", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/math-depth
func MathDepth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("math-depth", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/math-shift
func MathShift(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("math-shift", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/math-style
func MathStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("math-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/max-block-size
func MaxBlockSize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("max-block-size", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/max-height
func MaxHeight(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("max-height", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/max-inline-size
func MaxInlineSize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("max-inline-size", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/max-width
func MaxWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("max-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/min-block-size
func MinBlockSize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("min-block-size", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/min-height
func MinHeight(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("min-height", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/min-inline-size
func MinInlineSize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("min-inline-size", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/min-width
func MinWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("min-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode
func MixBlendMode(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("mix-blend-mode", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit
func ObjectFit(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("object-fit", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/object-position
func ObjectPosition(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("object-position", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/offset
func Offset(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("offset", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/offset-anchor
func OffsetAnchor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("offset-anchor", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/offset-distance
func OffsetDistance(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("offset-distance", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/offset-path
func OffsetPath(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("offset-path", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/offset-position
func OffsetPosition(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("offset-position", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/offset-rotate
func OffsetRotate(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("offset-rotate", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/opacity
func Opacity(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("opacity", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/order
func Order(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("order", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/orphans
func Orphans(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("orphans", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/outline
func Outline(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("outline", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/outline-color
func OutlineColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("outline-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/outline-offset
func OutlineOffset(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("outline-offset", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/outline-style
func OutlineStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("outline-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/outline-width
func OutlineWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("outline-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/overflow
func Overflow(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("overflow", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor
func OverflowAnchor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("overflow-anchor", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-block
func OverflowBlock(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("overflow-block", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-clip-margin
func OverflowClipMargin(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("overflow-clip-margin", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-inline
func OverflowInline(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("overflow-inline", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
func OverflowWrap(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("overflow-wrap", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x
func OverflowX(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("overflow-x", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y
func OverflowY(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("overflow-y", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
func OverscrollBehavior(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("overscroll-behavior", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-block
func OverscrollBehaviorBlock(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("overscroll-behavior-block", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-inline
func OverscrollBehaviorInline(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("overscroll-behavior-inline", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-x
func OverscrollBehaviorX(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("overscroll-behavior-x", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-y
func OverscrollBehaviorY(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("overscroll-behavior-y", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/padding
func Padding(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("padding", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block
func PaddingBlock(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("padding-block", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block-end
func PaddingBlockEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("padding-block-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block-start
func PaddingBlockStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("padding-block-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/padding-bottom
func PaddingBottom(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("padding-bottom", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline
func PaddingInline(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("padding-inline", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-end
func PaddingInlineEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("padding-inline-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-start
func PaddingInlineStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("padding-inline-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/padding-left
func PaddingLeft(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("padding-left", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/padding-right
func PaddingRight(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("padding-right", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/padding-top
func PaddingTop(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("padding-top", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-after
func PageBreakAfter(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("page-break-after", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-before
func PageBreakBefore(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("page-break-before", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-inside
func PageBreakInside(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("page-break-inside", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/paint-order
func PaintOrder(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("paint-order", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/perspective
func Perspective(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("perspective", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/perspective-origin
func PerspectiveOrigin(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("perspective-origin", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/place-content
func PlaceContent(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("place-content", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/place-items
func PlaceItems(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("place-items", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/place-self
func PlaceSelf(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("place-self", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events
func PointerEvents(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("pointer-events", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/position
func Position(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("position", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/print-color-adjust
func PrintColorAdjust(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("print-color-adjust", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/quotes
func Quotes(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("quotes", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/resize
func Resize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("resize", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/right
func Right(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("right", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/rotate
func Rotate(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("rotate", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap
func RowGap(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("row-gap", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-align
func RubyAlign(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("ruby-align", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-position
func RubyPosition(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("ruby-position", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scale
func Scale(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scale", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
func ScrollBehavior(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-behavior", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin
func ScrollMargin(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-margin", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-block
func ScrollMarginBlock(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-margin-block", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-block-end
func ScrollMarginBlockEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-margin-block-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-block-start
func ScrollMarginBlockStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-margin-block-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-bottom
func ScrollMarginBottom(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-margin-bottom", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-inline
func ScrollMarginInline(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-margin-inline", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-inline-end
func ScrollMarginInlineEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-margin-inline-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-inline-start
func ScrollMarginInlineStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-margin-inline-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-left
func ScrollMarginLeft(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-margin-left", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-right
func ScrollMarginRight(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-margin-right", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top
func ScrollMarginTop(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-margin-top", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding
func ScrollPadding(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-padding", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-block
func ScrollPaddingBlock(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-padding-block", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-block-end
func ScrollPaddingBlockEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-padding-block-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-block-start
func ScrollPaddingBlockStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-padding-block-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-bottom
func ScrollPaddingBottom(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-padding-bottom", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-inline
func ScrollPaddingInline(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-padding-inline", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-inline-end
func ScrollPaddingInlineEnd(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-padding-inline-end", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-inline-start
func ScrollPaddingInlineStart(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-padding-inline-start", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-left
func ScrollPaddingLeft(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-padding-left", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-right
func ScrollPaddingRight(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-padding-right", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top
func ScrollPaddingTop(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-padding-top", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-align
func ScrollSnapAlign(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-snap-align", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-stop
func ScrollSnapStop(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-snap-stop", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type
func ScrollSnapType(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scroll-snap-type", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color
func ScrollbarColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scrollbar-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter
func ScrollbarGutter(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scrollbar-gutter", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width
func ScrollbarWidth(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("scrollbar-width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/shape-image-threshold
func ShapeImageThreshold(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("shape-image-threshold", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/shape-margin
func ShapeMargin(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("shape-margin", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside
func ShapeOutside(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("shape-outside", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size
func TabSize(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("tab-size", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout
func TableLayout(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("table-layout", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-align
func TextAlign(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-align", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-align-last
func TextAlignLast(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-align-last", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-combine-upright
func TextCombineUpright(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-combine-upright", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration
func TextDecoration(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-decoration", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color
func TextDecorationColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-decoration-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-line
func TextDecorationLine(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-decoration-line", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip
func TextDecorationSkip(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-decoration-skip", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink
func TextDecorationSkipInk(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-decoration-skip-ink", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style
func TextDecorationStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-decoration-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness
func TextDecorationThickness(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-decoration-thickness", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis
func TextEmphasis(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-emphasis", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-color
func TextEmphasisColor(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-emphasis-color", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-position
func TextEmphasisPosition(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-emphasis-position", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-style
func TextEmphasisStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-emphasis-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-indent
func TextIndent(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-indent", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-justify
func TextJustify(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-justify", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation
func TextOrientation(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-orientation", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow
func TextOverflow(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-overflow", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering
func TextRendering(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-rendering", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow
func TextShadow(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-shadow", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust
func TextSizeAdjust(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-size-adjust", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform
func TextTransform(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-transform", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-offset
func TextUnderlineOffset(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-underline-offset", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-position
func TextUnderlinePosition(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("text-underline-position", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/top
func Top(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("top", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action
func TouchAction(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("touch-action", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/transform
func Transform(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("transform", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/transform-box
func TransformBox(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("transform-box", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin
func TransformOrigin(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("transform-origin", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/transform-style
func TransformStyle(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("transform-style", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/transition
func Transition(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("transition", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/transition-delay
func TransitionDelay(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("transition-delay", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/transition-duration
func TransitionDuration(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("transition-duration", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/transition-property
func TransitionProperty(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("transition-property", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/transition-timing-function
func TransitionTimingFunction(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("transition-timing-function", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/translate
func Translate(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("translate", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi
func UnicodeBidi(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("unicode-bidi", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/user-select
func UserSelect(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("user-select", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align
func VerticalAlign(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("vertical-align", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/view-transition-name
func ViewTransitionName(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("view-transition-name", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/visibility
func Visibility(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("visibility", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
func WhiteSpace(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("white-space", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/widows
func Widows(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("widows", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/width
func Width(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("width", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/will-change
func WillChange(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("will-change", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
func WordBreak(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("word-break", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/word-spacing
func WordSpacing(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("word-spacing", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode
func WritingMode(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("writing-mode", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/z-index
func ZIndex(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("z-index", v, u...)
}

// https://developer.mozilla.org/en-US/docs/Web/CSS/zoom
func Zoom(v any, u ...string) *ui.Ref[ui.StyleItem] {
	return makeRefStyle("zoom", v, u...)
}
