package dom

// This file implements KeyboardEvent interface
// https://developer.mozilla.org/zh-CN/docs/Web/API/MouseEvent

func (e Event) AltKey() bool {
	return e.Get("altKey").Bool()
}

// 0：主按键，通常指鼠标左键或默认值（译者注：如 document.getElementById('a').click() 这样触发就会是默认值）
// 1：辅助按键，通常指鼠标滚轮中键
// 2：次按键，通常指鼠标右键
// 3：第四个按钮，通常指浏览器后退按钮
// 4：第五个按钮，通常指浏览器的前进按钮
func (e Event) Button() int {
	return e.Get("button").Int()
}

// 一个数字，用来标识鼠标按下的一个或者多个按键。如果按下的键为多个，则值等于所有按键对应数值进行或 (|) 运算的结果。
//
// 0: 没有按键或者是没有初始化
// 1: 鼠标左键
// 2: 鼠标右键
// 4: 鼠标滚轮或者是中键
// 8: 第四按键 (通常是“浏览器后退”按键)
// 16 : 第五按键 (通常是“浏览器前进”)
func (e Event) Buttons() int {
	return e.Get("buttons").Int()
}

func (e Event) ClientX() int {
	return e.Get("clientX").Int()
}

func (e Event) ClientY() int {
	return e.Get("clientY").Int()
}

func (e Event) CtrlKey() bool {
	return e.Get("ctrlKey").Bool()
}

func (e Event) MetaKey() bool {
	return e.Get("metaKey").Bool()
}

func (e Event) MovementX() int {
	return e.Get("movementX").Int()
}

func (e Event) MovementY() int {
	return e.Get("movementY").Int()
}

// https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/mozInputSource
// Constant name	        Value	Description
// MOZ_SOURCE_UNKNOWN	0	    The input device is unknown.
// MOZ_SOURCE_MOUSE	    1	    The event was generated by a mouse (or mouse-like device).
// MOZ_SOURCE_PEN	    2	    The event was generated by a pen on a tablet.
// MOZ_SOURCE_ERASER	    3	    The event was generated by an eraser on a tablet.
// MOZ_SOURCE_CURSOR	    4	    The event was generated by a cursor.
// MOZ_SOURCE_TOUCH	    5	    The event was generated on a touch interface.
// MOZ_SOURCE_KEYBOARD	6	    The event was generated by a keyboard.
func (e Event) MozInputSource() int {
	return e.Get("mozInputSource").Int()
}

func (e Event) OffsetX() int {
	return e.Get("offsetX").Int()
}

func (e Event) OffsetY() int {
	return e.Get("offsetY").Int()
}

func (e Event) PageX() int {
	return e.Get("pageX").Int()
}

func (e Event) PageY() int {
	return e.Get("pageY").Int()
}

func (e Event) ScreenX() int {
	return e.Get("screenX").Int()
}

func (e Event) ScreenY() int {
	return e.Get("screenY").Int()
}

func (e Event) ShiftKey() bool {
	return e.Get("shiftKey").Bool()
}

func (e Event) X() int {
	return e.Get("x").Int()
}

func (e Event) Y() int {
	return e.Get("y").Int()
}
